from enum import StrEnum


class EligibilityReason(StrEnum):
    USER_NOT_ACTIVE = "USER_NOT_ACTIVE"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    ACCOUNT_TOO_NEW = "ACCOUNT_TOO_NEW"
    CAMPAIGN_PAUSED = "CAMPAIGN_PAUSED"
    CAMPAIGN_NOT_ACTIVE = "CAMPAIGN_NOT_ACTIVE"
    CAMPAIGN_NOT_STARTED = "CAMPAIGN_NOT_STARTED"
    CAMPAIGN_ENDED = "CAMPAIGN_ENDED"
    ROLE_NOT_ELIGIBLE = "ROLE_NOT_ELIGIBLE"
    ORGANIZATION_NOT_ELIGIBLE = "ORGANIZATION_NOT_ELIGIBLE"
    WORK_NOT_ELIGIBLE = "WORK_NOT_ELIGIBLE"
    VOTE_LIMIT_REACHED = "VOTE_LIMIT_REACHED"
    ALREADY_VOTED = "ALREADY_VOTED"


class EligibilityAction(StrEnum):
    CREATE = "CREATE"
    CHANGE = "CHANGE"
    REVOKE = "REVOKE"
